version: '3.8'

services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./:/app
      - models_data:/models
    env_file:
      - .env
    environment:
      - LLM_MODEL_PATH=/models/llama-2-7b-chat.Q4_K_M.gguf
      - MODEL_NAME=llama-2-7b-chat-gguf
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - db
      - ollama
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: cv-analyzer-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
      - APP_DB_USER=${DB_USER}
      - APP_DB_PASS=${DB_PASSWORD}
      - APP_DB_NAME=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: cv-analyzer-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 3G

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  models_data:
  ollama-data: